# Generated by Django 5.0.6 on 2024-12-19 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0003_alter_guest_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_guest', models.IntegerField()),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event_management.event')),
            ],
        ),
    ]
