# Generated by Django 5.0.6 on 2024-12-20 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0004_generatedinvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedinvite',
            name='invite_zip_download_url',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
